//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.01 at 10:28:14 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model.definition;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.ibm.mb.common.model.Group;

/**
 * <p>
 * Java class for WesbConversionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WesbConversionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/WESBArtifactsConversionToWMB}ConversionType">
 *       &lt;sequence>
 *         &lt;element name="sourceSelection" type="{http://www.ibm.com/mb/commonmodel}group"/>
 *         &lt;element name="resourceConfiguration" type="{http://www.ibm.com/mb/commonmodel}group"/>
 *         &lt;element name="globalOptions" type="{http://www.ibm.com/mb/commonmodel}group"/>
 *         &lt;element name="conversion" type="{http://www.ibm.com/mb/commonmodel}group"/>
 *         &lt;element name="summary" type="{http://www.ibm.com/mb/commonmodel}group"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WesbConversionType", propOrder = { "sourceSelection", "resourceConfiguration", "globalOptions", "conversion",
		"summary" })
public class WesbConversionType extends ConversionType {

	@XmlElement(required = true)
	protected Group sourceSelection;
	@XmlElement(required = true)
	protected Group resourceConfiguration;
	@XmlElement(required = true)
	protected Group globalOptions;
	@XmlElement(required = true)
	protected Group conversion;
	@XmlElement(required = true)
	protected Group summary;

	/**
	 * Gets the value of the sourceSelection property.
	 * 
	 * @return possible object is {@link Group }
	 * 
	 */
	public Group getSourceSelection() {
		return sourceSelection;
	}

	/**
	 * Sets the value of the sourceSelection property.
	 * 
	 * @param value
	 *            allowed object is {@link Group }
	 * 
	 */
	public void setSourceSelection(Group value) {
		this.sourceSelection = value;
	}

	/**
	 * Gets the value of the resourceConfiguration property.
	 * 
	 * @return possible object is {@link Group }
	 * 
	 */
	public Group getResourceConfiguration() {
		return resourceConfiguration;
	}

	/**
	 * Sets the value of the resourceConfiguration property.
	 * 
	 * @param value
	 *            allowed object is {@link Group }
	 * 
	 */
	public void setResourceConfiguration(Group value) {
		this.resourceConfiguration = value;
	}

	/**
	 * Gets the value of the globalOptions property.
	 * 
	 * @return possible object is {@link Group }
	 * 
	 */
	public Group getGlobalOptions() {
		return globalOptions;
	}

	/**
	 * Sets the value of the globalOptions property.
	 * 
	 * @param value
	 *            allowed object is {@link Group }
	 * 
	 */
	public void setGlobalOptions(Group value) {
		this.globalOptions = value;
	}

	/**
	 * Gets the value of the conversion property.
	 * 
	 * @return possible object is {@link Group }
	 * 
	 */
	public Group getConversion() {
		return conversion;
	}

	/**
	 * Sets the value of the conversion property.
	 * 
	 * @param value
	 *            allowed object is {@link Group }
	 * 
	 */
	public void setConversion(Group value) {
		this.conversion = value;
	}

	/**
	 * Gets the value of the summary property.
	 * 
	 * @return possible object is {@link Group }
	 * 
	 */
	public Group getSummary() {
		return summary;
	}

	/**
	 * Sets the value of the summary property.
	 * 
	 * @param value
	 *            allowed object is {@link Group }
	 * 
	 */
	public void setSummary(Group value) {
		this.summary = value;
	}

}
