//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.01 at 10:33:48 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model.mfc;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for mediationFlow complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="mediationFlow">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}import" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}promotedProperty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}interface" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}flow" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}extension" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="targetNamespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="multipleFiles" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mediationFlow", propOrder = { "_import", "promotedProperty", "reference", "_interface", "flow", "extension" })
public class MediationFlow {

	@XmlElement(name = "import")
	protected List<Import> _import;
	protected List<PromotedProperty> promotedProperty;
	protected List<Reference> reference;
	@XmlElement(name = "interface")
	protected List<Interface> _interface;
	@XmlElementRef(name = "flow", namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", type = JAXBElement.class)
	protected List<JAXBElement<? extends Flow>> flow;
	protected Extension extension;
	@XmlAttribute(name = "targetNamespace")
	protected String targetNamespace;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "multipleFiles")
	protected Boolean multipleFiles;

	/**
	 * Gets the value of the import property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the import property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getImport().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Import }
	 * 
	 * 
	 */
	public List<Import> getImport() {
		if (_import == null) {
			_import = new ArrayList<Import>();
		}
		return this._import;
	}

	/**
	 * Gets the value of the promotedProperty property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the promotedProperty property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPromotedProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PromotedProperty }
	 * 
	 * 
	 */
	public List<PromotedProperty> getPromotedProperty() {
		if (promotedProperty == null) {
			promotedProperty = new ArrayList<PromotedProperty>();
		}
		return this.promotedProperty;
	}

	/**
	 * Gets the value of the reference property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the reference property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getReference().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Reference }
	 * 
	 * 
	 */
	public List<Reference> getReference() {
		if (reference == null) {
			reference = new ArrayList<Reference>();
		}
		return this.reference;
	}

	/**
	 * Gets the value of the interface property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the interface property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInterface().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Interface }
	 * 
	 * 
	 */
	public List<Interface> getInterface() {
		if (_interface == null) {
			_interface = new ArrayList<Interface>();
		}
		return this._interface;
	}

	/**
	 * Gets the value of the flow property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the flow property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFlow().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link ResponseFlow }{@code >}
	 * {@link JAXBElement }{@code <}{@link RequestFlow }{@code >}
	 * {@link JAXBElement }{@code <}{@link ErrorFlow }{@code >}
	 * {@link JAXBElement }{@code <}{@link Subflow }{@code >} {@link JAXBElement }
	 * {@code <}{@link Flow }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<? extends Flow>> getFlow() {
		if (flow == null) {
			flow = new ArrayList<JAXBElement<? extends Flow>>();
		}
		return this.flow;
	}

	/**
	 * Gets the value of the extension property.
	 * 
	 * @return possible object is {@link Extension }
	 * 
	 */
	public Extension getExtension() {
		return extension;
	}

	/**
	 * Sets the value of the extension property.
	 * 
	 * @param value
	 *            allowed object is {@link Extension }
	 * 
	 */
	public void setExtension(Extension value) {
		this.extension = value;
	}

	/**
	 * Gets the value of the targetNamespace property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTargetNamespace() {
		return targetNamespace;
	}

	/**
	 * Sets the value of the targetNamespace property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTargetNamespace(String value) {
		this.targetNamespace = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the multipleFiles property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isMultipleFiles() {
		if (multipleFiles == null) {
			return false;
		} else {
			return multipleFiles;
		}
	}

	/**
	 * Sets the value of the multipleFiles property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setMultipleFiles(Boolean value) {
		this.multipleFiles = value;
	}

}
