//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.01 at 10:33:48 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model.mfc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.ibm.etools.mft.conversion.esb.model.mfc package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _ErrorFlow_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"errorFlow");
	private final static QName _AbstractProperty_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"abstractProperty");
	private final static QName _Property_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "property");
	private final static QName _Note_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "note");
	private final static QName _Extension_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"extension");
	private final static QName _Terminal_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "terminal");
	private final static QName _OutputTerminal_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"outputTerminal");
	private final static QName _RequestFlow_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"requestFlow");
	private final static QName _Row_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "row");
	private final static QName _FailTerminal_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"failTerminal");
	private final static QName _PromotedProperty_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"promotedProperty");
	private final static QName _Interface_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"interface");
	private final static QName _MediationFlow_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"mediationFlow");
	private final static QName _InputTerminal_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"inputTerminal");
	private final static QName _Operation_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"operation");
	private final static QName _Wire_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "wire");
	private final static QName _Import_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "import");
	private final static QName _Node_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "node");
	private final static QName _Subflow_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "subflow");
	private final static QName _Flow_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "flow");
	private final static QName _Table_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", "table");
	private final static QName _ResponseFlow_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"responseFlow");
	private final static QName _Reference_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"reference");
	private final static QName _Refinement_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow",
			"refinement");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.ibm.etools.mft.conversion.esb.model.mfc
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Node }
	 * 
	 */
	public Node createNode() {
		return new Node();
	}

	/**
	 * Create an instance of {@link Wire }
	 * 
	 */
	public Wire createWire() {
		return new Wire();
	}

	/**
	 * Create an instance of {@link Import }
	 * 
	 */
	public Import createImport() {
		return new Import();
	}

	/**
	 * Create an instance of {@link MediationFlow }
	 * 
	 */
	public MediationFlow createMediationFlow() {
		return new MediationFlow();
	}

	/**
	 * Create an instance of {@link InputTerminal }
	 * 
	 */
	public InputTerminal createInputTerminal() {
		return new InputTerminal();
	}

	/**
	 * Create an instance of {@link Operation }
	 * 
	 */
	public Operation createOperation() {
		return new Operation();
	}

	/**
	 * Create an instance of {@link Reference }
	 * 
	 */
	public Reference createReference() {
		return new Reference();
	}

	/**
	 * Create an instance of {@link Refinement }
	 * 
	 */
	public Refinement createRefinement() {
		return new Refinement();
	}

	/**
	 * Create an instance of {@link Subflow }
	 * 
	 */
	public Subflow createSubflow() {
		return new Subflow();
	}

	/**
	 * Create an instance of {@link Flow }
	 * 
	 */
	public Flow createFlow() {
		return new Flow();
	}

	/**
	 * Create an instance of {@link Table }
	 * 
	 */
	public Table createTable() {
		return new Table();
	}

	/**
	 * Create an instance of {@link AbstractProperty }
	 * 
	 */
	public AbstractProperty createAbstractProperty() {
		return new AbstractProperty();
	}

	/**
	 * Create an instance of {@link ResponseFlow }
	 * 
	 */
	public ResponseFlow createResponseFlow() {
		return new ResponseFlow();
	}

	/**
	 * Create an instance of {@link Note }
	 * 
	 */
	public Note createNote() {
		return new Note();
	}

	/**
	 * Create an instance of {@link Property }
	 * 
	 */
	public Property createProperty() {
		return new Property();
	}

	/**
	 * Create an instance of {@link ErrorFlow }
	 * 
	 */
	public ErrorFlow createErrorFlow() {
		return new ErrorFlow();
	}

	/**
	 * Create an instance of {@link Interface }
	 * 
	 */
	public Interface createInterface() {
		return new Interface();
	}

	/**
	 * Create an instance of {@link PromotedProperty }
	 * 
	 */
	public PromotedProperty createPromotedProperty() {
		return new PromotedProperty();
	}

	/**
	 * Create an instance of {@link FailTerminal }
	 * 
	 */
	public FailTerminal createFailTerminal() {
		return new FailTerminal();
	}

	/**
	 * Create an instance of {@link Row }
	 * 
	 */
	public Row createRow() {
		return new Row();
	}

	/**
	 * Create an instance of {@link Terminal }
	 * 
	 */
	public Terminal createTerminal() {
		return new Terminal();
	}

	/**
	 * Create an instance of {@link RequestFlow }
	 * 
	 */
	public RequestFlow createRequestFlow() {
		return new RequestFlow();
	}

	/**
	 * Create an instance of {@link OutputTerminal }
	 * 
	 */
	public OutputTerminal createOutputTerminal() {
		return new OutputTerminal();
	}

	/**
	 * Create an instance of {@link Extension }
	 * 
	 */
	public Extension createExtension() {
		return new Extension();
	}

	/**
	 * Create an instance of {@link OperationFlow }
	 * 
	 */
	public OperationFlow createOperationFlow() {
		return new OperationFlow();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ErrorFlow }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "errorFlow", substitutionHeadNamespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", substitutionHeadName = "flow")
	public JAXBElement<ErrorFlow> createErrorFlow(ErrorFlow value) {
		return new JAXBElement<ErrorFlow>(_ErrorFlow_QNAME, ErrorFlow.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link AbstractProperty }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "abstractProperty")
	public JAXBElement<AbstractProperty> createAbstractProperty(AbstractProperty value) {
		return new JAXBElement<AbstractProperty>(_AbstractProperty_QNAME, AbstractProperty.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Property }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "property", substitutionHeadNamespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", substitutionHeadName = "abstractProperty")
	public JAXBElement<Property> createProperty(Property value) {
		return new JAXBElement<Property>(_Property_QNAME, Property.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Note }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "note")
	public JAXBElement<Note> createNote(Note value) {
		return new JAXBElement<Note>(_Note_QNAME, Note.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Extension }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "extension")
	public JAXBElement<Extension> createExtension(Extension value) {
		return new JAXBElement<Extension>(_Extension_QNAME, Extension.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Terminal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "terminal")
	public JAXBElement<Terminal> createTerminal(Terminal value) {
		return new JAXBElement<Terminal>(_Terminal_QNAME, Terminal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link OutputTerminal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "outputTerminal")
	public JAXBElement<OutputTerminal> createOutputTerminal(OutputTerminal value) {
		return new JAXBElement<OutputTerminal>(_OutputTerminal_QNAME, OutputTerminal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link RequestFlow }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "requestFlow", substitutionHeadNamespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", substitutionHeadName = "flow")
	public JAXBElement<RequestFlow> createRequestFlow(RequestFlow value) {
		return new JAXBElement<RequestFlow>(_RequestFlow_QNAME, RequestFlow.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Row }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "row")
	public JAXBElement<Row> createRow(Row value) {
		return new JAXBElement<Row>(_Row_QNAME, Row.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FailTerminal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "failTerminal")
	public JAXBElement<FailTerminal> createFailTerminal(FailTerminal value) {
		return new JAXBElement<FailTerminal>(_FailTerminal_QNAME, FailTerminal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link PromotedProperty }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "promotedProperty", substitutionHeadNamespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", substitutionHeadName = "abstractProperty")
	public JAXBElement<PromotedProperty> createPromotedProperty(PromotedProperty value) {
		return new JAXBElement<PromotedProperty>(_PromotedProperty_QNAME, PromotedProperty.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Interface }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "interface")
	public JAXBElement<Interface> createInterface(Interface value) {
		return new JAXBElement<Interface>(_Interface_QNAME, Interface.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link MediationFlow }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "mediationFlow")
	public JAXBElement<MediationFlow> createMediationFlow(MediationFlow value) {
		return new JAXBElement<MediationFlow>(_MediationFlow_QNAME, MediationFlow.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link InputTerminal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "inputTerminal")
	public JAXBElement<InputTerminal> createInputTerminal(InputTerminal value) {
		return new JAXBElement<InputTerminal>(_InputTerminal_QNAME, InputTerminal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Operation }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "operation")
	public JAXBElement<Operation> createOperation(Operation value) {
		return new JAXBElement<Operation>(_Operation_QNAME, Operation.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Wire }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "wire")
	public JAXBElement<Wire> createWire(Wire value) {
		return new JAXBElement<Wire>(_Wire_QNAME, Wire.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Import }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "import")
	public JAXBElement<Import> createImport(Import value) {
		return new JAXBElement<Import>(_Import_QNAME, Import.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Node }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "node")
	public JAXBElement<Node> createNode(Node value) {
		return new JAXBElement<Node>(_Node_QNAME, Node.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Subflow }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "subflow", substitutionHeadNamespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", substitutionHeadName = "flow")
	public JAXBElement<Subflow> createSubflow(Subflow value) {
		return new JAXBElement<Subflow>(_Subflow_QNAME, Subflow.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "flow")
	public JAXBElement<Flow> createFlow(Flow value) {
		return new JAXBElement<Flow>(_Flow_QNAME, Flow.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Table }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "table", substitutionHeadNamespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", substitutionHeadName = "abstractProperty")
	public JAXBElement<Table> createTable(Table value) {
		return new JAXBElement<Table>(_Table_QNAME, Table.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ResponseFlow }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "responseFlow", substitutionHeadNamespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", substitutionHeadName = "flow")
	public JAXBElement<ResponseFlow> createResponseFlow(ResponseFlow value) {
		return new JAXBElement<ResponseFlow>(_ResponseFlow_QNAME, ResponseFlow.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Reference }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "reference")
	public JAXBElement<Reference> createReference(Reference value) {
		return new JAXBElement<Reference>(_Reference_QNAME, Reference.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Refinement }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow", name = "refinement")
	public JAXBElement<Refinement> createRefinement(Refinement value) {
		return new JAXBElement<Refinement>(_Refinement_QNAME, Refinement.class, null, value);
	}

}
