//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.01 at 10:33:48 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model.mfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for operation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="operation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}requestFlow"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}responseFlow" minOccurs="0"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}errorFlow" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operation", propOrder = { "requestFlow", "responseFlow", "errorFlow" })
public class Operation {

	@XmlElement(required = true)
	protected RequestFlow requestFlow;
	protected ResponseFlow responseFlow;
	protected ErrorFlow errorFlow;
	@XmlAttribute(name = "name")
	protected String name;

	/**
	 * Gets the value of the requestFlow property.
	 * 
	 * @return possible object is {@link RequestFlow }
	 * 
	 */
	public RequestFlow getRequestFlow() {
		return requestFlow;
	}

	/**
	 * Sets the value of the requestFlow property.
	 * 
	 * @param value
	 *            allowed object is {@link RequestFlow }
	 * 
	 */
	public void setRequestFlow(RequestFlow value) {
		this.requestFlow = value;
	}

	/**
	 * Gets the value of the responseFlow property.
	 * 
	 * @return possible object is {@link ResponseFlow }
	 * 
	 */
	public ResponseFlow getResponseFlow() {
		return responseFlow;
	}

	/**
	 * Sets the value of the responseFlow property.
	 * 
	 * @param value
	 *            allowed object is {@link ResponseFlow }
	 * 
	 */
	public void setResponseFlow(ResponseFlow value) {
		this.responseFlow = value;
	}

	/**
	 * Gets the value of the errorFlow property.
	 * 
	 * @return possible object is {@link ErrorFlow }
	 * 
	 */
	public ErrorFlow getErrorFlow() {
		return errorFlow;
	}

	/**
	 * Sets the value of the errorFlow property.
	 * 
	 * @param value
	 *            allowed object is {@link ErrorFlow }
	 * 
	 */
	public void setErrorFlow(ErrorFlow value) {
		this.errorFlow = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
