//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.01 at 10:33:48 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model.mfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for property complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="property">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/xmlns/prod/websphere/2010/MediationFlow}abstractProperty">
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="promotedPropertyGroup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="promotedPropertyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "property")
public class Property extends AbstractProperty {

	@XmlAttribute(name = "value")
	protected String value;
	@XmlAttribute(name = "promotedPropertyGroup")
	protected String promotedPropertyGroup;
	@XmlAttribute(name = "promotedPropertyName")
	protected String promotedPropertyName;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the promotedPropertyGroup property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPromotedPropertyGroup() {
		return promotedPropertyGroup;
	}

	/**
	 * Sets the value of the promotedPropertyGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPromotedPropertyGroup(String value) {
		this.promotedPropertyGroup = value;
	}

	/**
	 * Gets the value of the promotedPropertyName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPromotedPropertyName() {
		return promotedPropertyName;
	}

	/**
	 * Sets the value of the promotedPropertyName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPromotedPropertyName(String value) {
		this.promotedPropertyName = value;
	}

}
