//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.01 at 10:33:48 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model.mfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.ibm.etools.mft.conversion.esb.WESBConversionConstants;

/**
 * <p>
 * Java class for wire complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="wire">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="targetNode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetTerminal" type="{http://www.w3.org/2001/XMLSchema}string" default="in" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wire")
public class Wire implements WESBConversionConstants {

	@XmlAttribute(name = "targetNode", required = true)
	protected String targetNode;
	@XmlAttribute(name = "targetTerminal")
	protected String targetTerminal;

	/**
	 * Gets the value of the targetNode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTargetNode() {
		return targetNode;
	}

	/**
	 * Sets the value of the targetNode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTargetNode(String value) {
		this.targetNode = value;
	}

	/**
	 * Gets the value of the targetTerminal property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTargetTerminal() {
		if (targetTerminal == null) {
			return IN_TERMINAL; //$NON-NLS-1$
		} else {
			return targetTerminal;
		}
	}

	/**
	 * Sets the value of the targetTerminal property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTargetTerminal(String value) {
		this.targetTerminal = value;
	}

}
