//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.04 at 02:12:03 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ConversionResult complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ConversionResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sourceTargetMap" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="convertedResources" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConversionResult", propOrder = { "summary", "error", "trace", "sourceTargetMap", "convertedResources" })
public class ConversionResult {

	@XmlElement(required = true)
	protected String summary;
	@XmlElement(required = true)
	protected String error;
	@XmlElement(required = true)
	protected String trace;
	@XmlElement(required = true)
	protected String sourceTargetMap;
	@XmlElement(required = true)
	protected String convertedResources;

	/**
	 * Gets the value of the summary property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * Sets the value of the summary property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSummary(String value) {
		this.summary = value;
	}

	/**
	 * Gets the value of the error property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getError() {
		return error;
	}

	/**
	 * Sets the value of the error property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setError(String value) {
		this.error = value;
	}

	/**
	 * Gets the value of the trace property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTrace() {
		return trace;
	}

	/**
	 * Sets the value of the trace property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTrace(String value) {
		this.trace = value;
	}

	/**
	 * Gets the value of the sourceTargetMap property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSourceTargetMap() {
		return sourceTargetMap;
	}

	/**
	 * Sets the value of the sourceTargetMap property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSourceTargetMap(String value) {
		this.sourceTargetMap = value;
	}

	/**
	 * Gets the value of the convertedResources property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConvertedResources() {
		return convertedResources;
	}

	/**
	 * Sets the value of the convertedResources property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setConvertedResources(String value) {
		this.convertedResources = value;
	}

}
