//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 04:05:04 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for GlobalConfigurationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GlobalConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="primitiveConverters" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}PrimitiveConverter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pathMappings" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}PathMapping" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bindingConverters" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}BindingConverter" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="includeReferencedProject" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="mergeResult" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlobalConfigurationType", propOrder = { "primitiveConverters", "pathMappings", "bindingConverters" })
public class GlobalConfigurationType {

	protected List<PrimitiveConverter> primitiveConverters;
	protected List<PathMapping> pathMappings;
	protected List<BindingConverter> bindingConverters;
	@XmlAttribute(name = "includeReferencedProject", required = true)
	protected boolean includeReferencedProject;
	@XmlAttribute(name = "mergeResult", required = true)
	protected boolean mergeResult;

	/**
	 * Gets the value of the primitiveConverters property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the primitiveConverters property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPrimitiveConverters().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PrimitiveConverter }
	 * 
	 * 
	 */
	public List<PrimitiveConverter> getPrimitiveConverters() {
		if (primitiveConverters == null) {
			primitiveConverters = new ArrayList<PrimitiveConverter>();
		}
		return this.primitiveConverters;
	}

	/**
	 * Gets the value of the pathMappings property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the pathMappings property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPathMappings().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PathMapping }
	 * 
	 * 
	 */
	public List<PathMapping> getPathMappings() {
		if (pathMappings == null) {
			pathMappings = new ArrayList<PathMapping>();
		}
		return this.pathMappings;
	}

	/**
	 * Gets the value of the bindingConverters property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the bindingConverters property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBindingConverters().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BindingConverter }
	 * 
	 * 
	 */
	public List<BindingConverter> getBindingConverters() {
		if (bindingConverters == null) {
			bindingConverters = new ArrayList<BindingConverter>();
		}
		return this.bindingConverters;
	}

	/**
	 * Gets the value of the includeReferencedProject property.
	 * 
	 */
	public boolean isIncludeReferencedProject() {
		return includeReferencedProject;
	}

	/**
	 * Sets the value of the includeReferencedProject property.
	 * 
	 */
	public void setIncludeReferencedProject(boolean value) {
		this.includeReferencedProject = value;
	}

	/**
	 * Gets the value of the mergeResult property.
	 * 
	 */
	public boolean isMergeResult() {
		return mergeResult;
	}

	/**
	 * Sets the value of the mergeResult property.
	 * 
	 */
	public void setMergeResult(boolean value) {
		this.mergeResult = value;
	}

}
