//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 04:05:04 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.ibm.etools.mft.conversion.esb.model
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _WesbConversionData_QNAME = new QName(
			"http://www.ibm.com/WESBArtifactsConversionToWMB", "wesbConversionData"); //$NON-NLS-1$ //$NON-NLS-2$

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.ibm.etools.mft.conversion.esb.model
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link WESBConversionDataType }
	 * 
	 */
	public WESBConversionDataType createWESBConversionDataType() {
		return new WESBConversionDataType();
	}

	/**
	 * Create an instance of {@link Converter }
	 * 
	 */
	public Converter createConverter() {
		return new Converter();
	}

	/**
	 * Create an instance of {@link MFCComponentResource }
	 * 
	 */
	public MFCComponentResource createMFCComponentResource() {
		return new MFCComponentResource();
	}

	/**
	 * Create an instance of {@link ExportResource }
	 * 
	 */
	public ExportResource createExportResource() {
		return new ExportResource();
	}

	/**
	 * Create an instance of {@link PathMapping }
	 * 
	 */
	public PathMapping createPathMapping() {
		return new PathMapping();
	}

	/**
	 * Create an instance of {@link ComponentResource }
	 * 
	 */
	public ComponentResource createComponentResource() {
		return new ComponentResource();
	}

	/**
	 * Create an instance of {@link ClassDefinition }
	 * 
	 */
	public ClassDefinition createClassDefinition() {
		return new ClassDefinition();
	}

	/**
	 * Create an instance of {@link WESBResource }
	 * 
	 */
	public WESBResource createWESBResource() {
		return new WESBResource();
	}

	/**
	 * Create an instance of {@link GlobalConfigurationType }
	 * 
	 */
	public GlobalConfigurationType createGlobalConfigurationType() {
		return new GlobalConfigurationType();
	}

	/**
	 * Create an instance of {@link ImportResource }
	 * 
	 */
	public ImportResource createImportResource() {
		return new ImportResource();
	}

	/**
	 * Create an instance of {@link WESBMaps }
	 * 
	 */
	public WESBMaps createWESBMaps() {
		return new WESBMaps();
	}

	/**
	 * Create an instance of {@link WESBJavas }
	 * 
	 */
	public WESBJavas createWESBJavas() {
		return new WESBJavas();
	}

	/**
	 * Create an instance of {@link WESBSchemas }
	 * 
	 */
	public WESBSchemas createWESBSchemas() {
		return new WESBSchemas();
	}

	/**
	 * Create an instance of {@link PrimitiveConverter }
	 * 
	 */
	public PrimitiveConverter createPrimitiveConverter() {
		return new PrimitiveConverter();
	}

	/**
	 * Create an instance of {@link BindingConverter }
	 * 
	 */
	public BindingConverter createBindingConverter() {
		return new BindingConverter();
	}

	/**
	 * Create an instance of {@link WESBProject }
	 * 
	 */
	public WESBProject createWESBProject() {
		return new WESBProject();
	}

	/**
	 * Create an instance of {@link SCAModule }
	 * 
	 */
	public SCAModule createSCAModule() {
		return new SCAModule();
	}

	/**
	 * Create an instance of {@link WESBMap }
	 * 
	 */
	public WESBMap createWESBMap() {
		return new WESBMap();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link WESBConversionDataType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ibm.com/WESBArtifactsConversionToWMB", name = "wesbConversionData")
	public JAXBElement<WESBConversionDataType> createWesbConversionData(WESBConversionDataType value) {
		return new JAXBElement<WESBConversionDataType>(_WesbConversionData_QNAME, WESBConversionDataType.class, null, value);
	}

}
