//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 04:05:04 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ibm.com/WESBArtifactsConversionToWMB", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ibm.etools.mft.conversion.esb.model;

