//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 04:05:04 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WESBConversionDataType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WESBConversionDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceProjects" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}WESBProject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="globalConfiguration" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}GlobalConfigurationType"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="resultOutOfSync" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WESBConversionDataType", propOrder = { "sourceProjects", "globalConfiguration", "result" })
public class WESBConversionDataType {

	protected List<WESBProject> sourceProjects;
	@XmlElement(required = true)
	protected GlobalConfigurationType globalConfiguration;
	@XmlElement(required = true)
	protected String result;
	@XmlAttribute(name = "resultOutOfSync", required = true)
	protected boolean resultOutOfSync;

	/**
	 * Gets the value of the sourceProjects property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sourceProjects property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSourceProjects().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link WESBProject }
	 * 
	 * 
	 */
	public List<WESBProject> getSourceProjects() {
		if (sourceProjects == null) {
			sourceProjects = new ArrayList<WESBProject>();
		}
		return this.sourceProjects;
	}

	/**
	 * Gets the value of the globalConfiguration property.
	 * 
	 * @return possible object is {@link GlobalConfigurationType }
	 * 
	 */
	public GlobalConfigurationType getGlobalConfiguration() {
		return globalConfiguration;
	}

	/**
	 * Sets the value of the globalConfiguration property.
	 * 
	 * @param value
	 *            allowed object is {@link GlobalConfigurationType }
	 * 
	 */
	public void setGlobalConfiguration(GlobalConfigurationType value) {
		this.globalConfiguration = value;
	}

	/**
	 * Gets the value of the result property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResult() {
		return result;
	}

	/**
	 * Sets the value of the result property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResult(String value) {
		this.result = value;
	}

	/**
	 * Gets the value of the resultOutOfSync property.
	 * 
	 */
	public boolean isResultOutOfSync() {
		return resultOutOfSync;
	}

	/**
	 * Sets the value of the resultOutOfSync property.
	 * 
	 */
	public void setResultOutOfSync(boolean value) {
		this.resultOutOfSync = value;
	}

}
