//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 04:05:04 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WESBMaps complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WESBMaps">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/WESBArtifactsConversionToWMB}WESBResource">
 *       &lt;sequence>
 *         &lt;element name="allMaps" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}WESBMap" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WESBMaps", propOrder = { "allMaps" })
public class WESBMaps extends WESBResource {

	protected List<WESBMap> allMaps;

	/**
	 * Gets the value of the allMaps property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the allMaps property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAllMaps().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link WESBMap }
	 * 
	 * 
	 */
	public List<WESBMap> getAllMaps() {
		if (allMaps == null) {
			allMaps = new ArrayList<WESBMap>();
		}
		return this.allMaps;
	}

}
