//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 04:05:04 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WESBMap complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WESBMap">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/WESBArtifactsConversionToWMB}WESBResource">
 *       &lt;sequence>
 *         &lt;element name="usages" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tobeConverted" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="mapType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WESBMap", propOrder = { "usages" })
public class WESBMap extends WESBResource {

	protected List<String> usages;
	@XmlAttribute(name = "tobeConverted", required = true)
	protected boolean tobeConverted;
	@XmlAttribute(name = "mapType")
	protected String mapType;

	/**
	 * Gets the value of the usages property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the usages property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getUsages().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getUsages() {
		if (usages == null) {
			usages = new ArrayList<String>();
		}
		return this.usages;
	}

	/**
	 * Gets the value of the tobeConverted property.
	 * 
	 */
	public boolean isTobeConverted() {
		return tobeConverted;
	}

	/**
	 * Sets the value of the tobeConverted property.
	 * 
	 */
	public void setTobeConverted(boolean value) {
		this.tobeConverted = value;
	}

	/**
	 * Gets the value of the mapType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMapType() {
		return mapType;
	}

	/**
	 * Sets the value of the mapType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMapType(String value) {
		this.mapType = value;
	}

}
