//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 04:05:04 PM EDT 
//

package com.ibm.etools.mft.conversion.esb.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WESBProject complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WESBProject">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/WESBArtifactsConversionToWMB}WESBResource">
 *       &lt;sequence>
 *         &lt;element name="applicableLandingPoints" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="maps" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}WESBMaps"/>
 *         &lt;element name="javas" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}WESBJavas"/>
 *         &lt;element name="schemas" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}WESBSchemas"/>
 *         &lt;element name="module" type="{http://www.ibm.com/WESBArtifactsConversionToWMB}SCAModule"/>
 *       &lt;/sequence>
 *       &lt;attribute name="landingPoint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="toConvert" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WESBProject", propOrder = { "applicableLandingPoints", "maps", "javas", "schemas", "module" })
public class WESBProject extends WESBResource {

	protected List<String> applicableLandingPoints;
	@XmlElement(required = true)
	protected WESBMaps maps;
	@XmlElement(required = true)
	protected WESBJavas javas;
	@XmlElement(required = true)
	protected WESBSchemas schemas;
	@XmlElement(required = true)
	protected SCAModule module;
	@XmlAttribute(name = "landingPoint")
	protected String landingPoint;
	@XmlAttribute(name = "targetName")
	protected String targetName;
	@XmlAttribute(name = "toConvert", required = true)
	protected boolean toConvert;

	/**
	 * Gets the value of the applicableLandingPoints property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the applicableLandingPoints property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getApplicableLandingPoints().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getApplicableLandingPoints() {
		if (applicableLandingPoints == null) {
			applicableLandingPoints = new ArrayList<String>();
		}
		return this.applicableLandingPoints;
	}

	/**
	 * Gets the value of the maps property.
	 * 
	 * @return possible object is {@link WESBMaps }
	 * 
	 */
	public WESBMaps getMaps() {
		return maps;
	}

	/**
	 * Sets the value of the maps property.
	 * 
	 * @param value
	 *            allowed object is {@link WESBMaps }
	 * 
	 */
	public void setMaps(WESBMaps value) {
		this.maps = value;
	}

	/**
	 * Gets the value of the javas property.
	 * 
	 * @return possible object is {@link WESBJavas }
	 * 
	 */
	public WESBJavas getJavas() {
		return javas;
	}

	/**
	 * Sets the value of the javas property.
	 * 
	 * @param value
	 *            allowed object is {@link WESBJavas }
	 * 
	 */
	public void setJavas(WESBJavas value) {
		this.javas = value;
	}

	/**
	 * Gets the value of the schemas property.
	 * 
	 * @return possible object is {@link WESBSchemas }
	 * 
	 */
	public WESBSchemas getSchemas() {
		return schemas;
	}

	/**
	 * Sets the value of the schemas property.
	 * 
	 * @param value
	 *            allowed object is {@link WESBSchemas }
	 * 
	 */
	public void setSchemas(WESBSchemas value) {
		this.schemas = value;
	}

	/**
	 * Gets the value of the module property.
	 * 
	 * @return possible object is {@link SCAModule }
	 * 
	 */
	public SCAModule getModule() {
		return module;
	}

	/**
	 * Sets the value of the module property.
	 * 
	 * @param value
	 *            allowed object is {@link SCAModule }
	 * 
	 */
	public void setModule(SCAModule value) {
		this.module = value;
	}

	/**
	 * Gets the value of the landingPoint property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLandingPoint() {
		return landingPoint;
	}

	/**
	 * Sets the value of the landingPoint property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLandingPoint(String value) {
		this.landingPoint = value;
	}

	/**
	 * Gets the value of the targetName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTargetName() {
		return targetName;
	}

	/**
	 * Sets the value of the targetName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTargetName(String value) {
		this.targetName = value;
	}

	/**
	 * Gets the value of the toConvert property.
	 * 
	 */
	public boolean isToConvert() {
		return toConvert;
	}

	/**
	 * Sets the value of the toConvert property.
	 * 
	 */
	public void setToConvert(boolean value) {
		this.toConvert = value;
	}

}
